name = "Academic"
license = "MIT"
description = "This is the website for the Quantum Information Group of BITS Pilani, Goa Campus."
homepage = "https://github.com/wowchemy/starter-hugo-academic/"
demosite = "https://wowchemy.com/hugo-themes/"
tags = ["quantum",
        "qiskit",
        "bits",
        "bitsgoa",
        "quantum-computing",
        ]

[author]
  name = "Pi"
  homepage = "https://github.com/git-pi-e"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
